#!/bin/bash

#
# Exit if a command fails.
#
set -e

# https://git.kernel.org/pub/scm/git/git
sudo apt install -y git
sudo apt install -y gitk

# https://gitlab.gnome.org/GNOME/dconf
sudo apt install -y dconf-editor

# https://sourceforge.net/projects/preload
sudo apt install -y preload

# https://packages.debian.org/stable/build-essential
sudo apt install -y build-essential

# https://github.com/mvo5/synaptic
sudo apt install -y synaptic

# https://gitlab.freedesktop.org/libinput/libinput
sudo apt install -y libinput-tools

# https://gitlab.freedesktop.org/libevdev/evtest
sudo apt install -y evtest

# https://gitlab.freedesktop.org/xorg/app/xinput
sudo apt install -y xinput

# https://gitlab.freedesktop.org/xorg/lib/libxcb
sudo apt install -y libxcb-xtest0

# https://github.com/libarchive/libarchive
sudo apt install -y libarchive-tools

# https://github.com/brndnmtthws/conky
sudo apt install -y conky

# https://github.com/numixproject
sudo apt install -y numix-gtk-theme
sudo apt install -y numix-icon-theme
sudo apt install -y numix-icon-theme-circle

# https://github.com/dylanaraps/neofetch
sudo apt install -y neofetch

# https://github.com/gnome-terminator/terminator
sudo apt install -y terminator

# https://github.com/vim/vim
sudo apt install -y vim

# https://packages.debian.org/stable/xxd
sudo apt install -y xxd

# https://github.com/neovim/neovim
sudo apt install -y neovim

# https://savannah.gnu.org/projects/emacs
sudo apt install -y emacs

# https://gitlab.gnome.org/World/gedit/gedit
sudo apt install -y gedit
sudo apt install -y gedit-plugins

# https://packages.debian.org/stable/atop
sudo apt install -y atop

# https://github.com/htop-dev/htop
sudo apt install -y htop

# https://sourceforge.net/projects/nmon
sudo apt install -y nmon

# https://github.com/sharkdp/bat
sudo apt install -y bat

# https://github.com/andreafrancia/trash-cli
sudo apt install -y trash-cli

# https://github.com/tmux/tmux
sudo apt install -y tmux

# https://github.com/curl/curl
sudo apt install -y curl

# https://github.com/BurntSushi/ripgrep
sudo apt install -y ripgrep

# https://sourceforge.net/projects/zsh
sudo apt install -y zsh

# https://github.com/fish-shell/fish-shell
sudo apt install -y fish

# https://gitlab.gnome.org/GNOME/gparted
sudo apt install -y gparted

# https://git.kernel.org/pub/scm/network/ethtool/ethtool
sudo apt install -y ethtool

# https://github.com/lyonel/lshw
sudo apt install -y lshw

# https://github.com/lpereira/hardinfo
sudo apt install -y hardinfo

# https://github.com/openSUSE/hwinfo
sudo apt install -y hwinfo

# https://g.blicky.net/ncdu
sudo apt install -y ncdu

# https://git.cgsecurity.org/cgit/testdisk
sudo apt install -y testdisk

# https://github.com/Conservatory/wmctrl
sudo apt install -y wmctrl

# https://github.com/psibi/tldr-hs
sudo apt install -y tldr

# https://packages.debian.org/stable/secure-delete
sudo apt install -y secure-delete

# https://github.com/berke/wipe
sudo apt install -y wipe

# https://github.com/derf/feh
sudo apt install -y feh

# https://github.com/lavv17/le
sudo apt install -y le

# https://github.com/zyedidia/micro
sudo apt install -y micro

# https://github.com/geany/geany
sudo apt install -y geany

# https://invent.kde.org/graphics/okular
sudo apt install -y okular

# https://packages.debian.org/stable/libreoffice-java-common
sudo apt install -y libreoffice-java-common

# https://github.com/imagemagick/imagemagick
sudo apt install -y imagemagick

# https://sourceforge.net/projects/graphicsmagick
sudo apt install -y graphicsmagick

# https://github.com/exiftool/exiftool
sudo apt install -y libimage-exiftool-perl

# https://github.com/abishekvashok/cmatrix
sudo apt install -y cmatrix

# https://packages.debian.org/stable/festival
sudo apt install -y festival

# https://github.com/mtoyoda/sl
sudo apt install -y sl

# https://packages.debian.org/stable/cowsay
sudo apt install -y cowsay

# https://sourceforge.net/projects/aa-project
sudo apt install -y bb

# https://github.com/Talinx/jp2a
sudo apt install -y jp2a

# https://github.com/Hjdskes/gcolor3
sudo apt install -y gcolor3

# https://gitlab.com/graphviz/graphviz
sudo apt install -y graphviz

# https://sourceforge.net/projects/p7zip
sudo apt install -y p7zip
sudo apt install -y p7zip-full
sudo apt install -y p7zip-rar

# https://sourceforge.net/projects/sevenzip
sudo apt install -y lzma
sudo apt install -y lzma-dev

# https://github.com/openssl/openssl
sudo apt install -y libssl-dev

# https://github.com/c-ares/c-ares
sudo apt install -y libc-ares2

# https://github.com/MediaArea/MediaInfo
sudo apt install -y libmediainfo0v5

# https://github.com/MediaArea/ZenLib
sudo apt install -y libzen0v5

# https://git.launchpad.net/qpdfview
sudo apt install -y qpdfview

# https://github.com/pdfpc/pdfpc
sudo apt install -y pdf-presenter-console

# https://filezilla-project.org
sudo apt install -y filezilla

# https://github.com/thewml/website-meta-language
sudo apt install -y wml

# https://github.com/jgm/pandoc
sudo apt install -y pandoc

# https://sourceforge.net/projects/qpdf
sudo apt install -y qpdf

# https://gitlab.com/pdftk-java/pdftk
sudo apt install -y pdftk-java

# https://www.cups-pdf.de
sudo apt install -y printer-driver-cups-pdf

# https://github.com/FFmpeg/FFmpeg
sudo apt install -y ffmpeg

# https://github.com/HandBrake/HandBrake
sudo apt install -y handbrake

# https://sourceforge.net/projects/mp3wrap
sudo apt install -y mp3wrap

# https://github.com/flameshot-org/flameshot
sudo apt install -y flameshot

# https://github.com/fastfetch-cli/fastfetch
# https://github.com/aristocratos/btop
# https://github.com/alacritty/alacritty
# https://github.com/conda/conda

# https://github.com/microsoft/vscode
# https://github.com/syl20bnr/spacemacs
# https://github.com/JetBrains/intellij-community
# https://github.com/pulsar-edit/pulsar
# https://github.com/apache/netbeans
# https://github.com/phcode-dev/phoenix
# https://github.com/Komodo/KomodoEdit
# https://invent.kde.org/utilities/kate
# https://github.com/eclipse-platform/eclipse.platform

# https://github.com/audacity/audacity
# https://github.com/Ardour/ardour
# https://github.com/videolan/vlc
# https://github.com/nomacs/nomacs
# https://sourceforge.net/projects/scribus
# https://github.com/fontforge/fontforge
# https://gitlab.gnome.org/GNOME/gimp
# https://invent.kde.org/graphics/krita
# https://github.com/darktable-org/darktable
# https://github.com/PintaProject/Pinta
# https://invent.kde.org/graphics/kolourpaint
# https://invent.kde.org/multimedia/kdenlive
# https://github.com/mltframework/shotcut
# https://github.com/OpenShot/openshot-qt
# https://github.com/blender/blender
# https://github.com/NatronGitHub/Natron
# https://github.com/ggarra13/mrv2
# https://github.com/darbyjohnston/DJV
# https://github.com/musescore/MuseScore
# https://github.com/godotengine/godot
# https://github.com/obsproject/obs-studio
# https://github.com/ventoy/Ventoy
# https://github.com/balena-io/etcher

# https://github.com/LibreOffice/core
# https://github.com/ONLYOFFICE/DesktopEditors
# https://github.com/apache/openoffice

# https://github.com/latex3/latex2e
# https://github.com/typst/typst

# https://github.com/zotero/zotero
# https://github.com/retorquere/zotero-better-bibtex

# https://github.com/python/cpython
# https://github.com/openjdk/jdk
# https://github.com/golang/go
# https://github.com/rust-lang/rust
# https://github.com/JetBrains/kotlin
# https://github.com/lua/lua
# https://github.com/ruby/ruby
# https://github.com/swiftlang/swift
# https://github.com/scala/scala
# https://github.com/Perl/perl5
# https://github.com/JuliaLang/julia
# https://github.com/ocaml/ocaml
# https://github.com/crystal-lang/crystal

# https://dev.gnupg.org/source/gnupg
# https://gitlab.com/cryptsetup/cryptsetup
# https://github.com/rclone/rclone
# https://github.com/FiloSottile/age
# https://github.com/cryptomator/cryptomator
# https://github.com/veracrypt/VeraCrypt
# https://github.com/jedisct1/minisign
# https://github.com/Picocrypt/Picocrypt
# https://github.com/google/fscrypt
# https://github.com/CipherShed/CipherShed
# https://github.com/DavidXanatos/DiskCryptor
# https://github.com/samuel-lucas6/Kryptor

# https://invent.kde.org/utilities/kwalletmanager
# https://git.zx2c4.com/password-store
# https://gitlab.com/spectre.app/cli
# https://github.com/ProtonMail/WebClients
# https://sourceforge.net/projects/keepass
# https://github.com/keepassxreboot/keepassxc
# https://github.com/bitwarden/server
# https://github.com/keeweb/keeweb
# https://github.com/lesspass/lesspass
# https://github.com/padloc/padloc
# https://github.com/pwsafe/pwsafe
